### PR TITLE
.NET Core

### PR DESCRIPTION
**Pull request by slang25**
Things to note:
- I've targeted `netstandard2.0` and `netcoreapp2.0`, I am seeing less value these days multi-targeting with full framework.
- The core supporting `CommandLineParser` is in beta, I have gone to the repo and offered help there.
- In migrating the tests, I noticed that there was an assertion against a synchronous AWS SDK api, which is now wont compile, "fixing it" by pointing to the async method (which actually is used) breaks it. So I have ignored the test for now: https://github.com/justeat/AwsWatchman/pull/78/files#diff-eaec889e7526378c98488b480fcefe14R12
- I haven't tested this manually or ran the integration tests.
- `AppConfigAWSCredentials` is no longer a thing when targetting core, so I've removed it.: https://github.com/justeat/AwsWatchman/pull/78/files#diff-b95d576261fcfe662cf48708bed36492L56
- README needs updating.

### CODE REVIEW

**Comment by AnthonySteele** [comment]
It's about time! So long as we can still run this on our internal build agents.

**Comment by slang25** [comment]
I'll have a go with our beta pool agents. Could probably also do with a appveyor and/or travis build given this is open now.

**Comment by AnthonySteele** [comment]
Agreed

**Comment by AnthonySteele** [comment]
For CI purposes, the test projects must include a ref to `NUnit.Console` so that the teamCity can use that runner

**Pull request merged**
