### PR TITLE
Add support for RDS Cluster level metrics to AWSWatchman

### PR DESCRIPTION
**Pull request by wieruszewski**

### CODE REVIEW

**Comment by tomhaigh** [comment]
Thanks for the PR. Please could you update the documentation and add at least one end to end test (in `Watchman.Tests` similar to other services)?

**Comment by wieruszewski** [comment]
@tomhaigh thanks for looking into this PR so promptly. I will work on the requested changes and will let you know once it's ready.

**Comment by wieruszewski** [comment]
@tomhaigh I addressed now requested changes - could you please re-check this PR?

**Comment by tomhaigh** [comment]
Thanks - looks fine - have you tested it anywhere?

**Comment by wieruszewski** [comment]
Yes - I confirm that I tested it manually against AWS account too.

**Pull request merged**
